apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-vlkberlin-net-tls
spec:
  secretName: k8s-vlkberlin-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.vlkberlin.net
  dnsNames:
    - k8s.vlkberlin.net
    - www.k8s.vlkberlin.net
  acme:
      config:
        - http01:
          ingressClass: nginx
        domains:
          - k8s.vlkberlin.net
          - www.k8s.vlkberlin.net
